apiVersion: v1
kind: Service
metadata:
  name: java-cobrand-service
spec:
  selector:
    app: hello-world
    version: "v1"
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
