apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-jenkins-2
  labels:
    app: hello-world
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 0 
       maxSurge: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        version: "v2"
    spec:
      containers:
      - name: hello-world-pod
        #image:  asia.gcr.io/abstract-stream-316904/java-cobrand-demo:jenkins
        image: testjfrogd.jfrog.io/default-docker-virtual/gradle-image:15
        ports: 
        - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret

